version: '3.8'

services:
  db:
    image: postgres:15
    container_name: my_postgres_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: mypguser
      POSTGRES_PASSWORD: mypgpassword
      POSTGRES_DB: mypgdatabase
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U mypguser -d mypgdatabase"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: